In [ ]:
import torch


In [ ]:
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
    print("cuda is available")
    print(torch.cuda.get_device_name(0))
else:
    print("cuda is not available")

cuda is available
Tesla T4


In [ ]:
a=torch.empty(2,3)

In [ ]:
type(a)

torch.Tensor

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.rand(2,3)

tensor([[0.8542, 0.2202, 0.7090],
        [0.0828, 0.4918, 0.9044]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])