In [3]:
!pip install nltk

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
from torch.utils.data import Dataset,DataLoader
from nltk.tokenize import word_tokenize
import nltk

In [3]:
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [4]:
document = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""


In [5]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [6]:
tokens=word_tokenize(document.lower())

In [9]:
# Counter(tokens).keys()

In [7]:
vocab={'<unk>':0}

for token in Counter(tokens).keys():
  if token not in vocab:
    vocab[token]=len(vocab)

vocab

{'<unk>': 0,
 'about': 1,
 'the': 2,
 'program': 3,
 'what': 4,
 'is': 5,
 'course': 6,
 'fee': 7,
 'for': 8,
 'data': 9,
 'science': 10,
 'mentorship': 11,
 '(': 12,
 'dsmp': 13,
 '2023': 14,
 ')': 15,
 'follows': 16,
 'a': 17,
 'monthly': 18,
 'subscription': 19,
 'model': 20,
 'where': 21,
 'you': 22,
 'have': 23,
 'to': 24,
 'make': 25,
 'payments': 26,
 'of': 27,
 'rs': 28,
 '799/month': 29,
 '.': 30,
 'total': 31,
 'duration': 32,
 '?': 33,
 '7': 34,
 'months': 35,
 'so': 36,
 'becomes': 37,
 '799': 38,
 '*': 39,
 '=': 40,
 '5600': 41,
 'approx': 42,
 'syllabus': 43,
 'we': 44,
 'will': 45,
 'be': 46,
 'covering': 47,
 'following': 48,
 'modules': 49,
 ':': 50,
 'python': 51,
 'fundamentals': 52,
 'libraries': 53,
 'analysis': 54,
 'sql': 55,
 'maths': 56,
 'machine': 57,
 'learning': 58,
 'ml': 59,
 'algorithms': 60,
 'practical': 61,
 'mlops': 62,
 'case': 63,
 'studies': 64,
 'can': 65,
 'check': 66,
 'detailed': 67,
 'here': 68,
 '-': 69,
 'https': 70,
 '//learnwith.campusx.i

In [10]:
len(vocab)

289

In [11]:
input_sentences=document.split('\n')

In [12]:
len(input_sentences)

78

In [13]:
def text_to_indices(sentence,vocab):
  numerical_sentence=[]

  for token in sentence:
    if token in vocab:
      numerical_sentence.append(vocab[token])
    else:
      numerical_sentence.append(vocab['<unk>'])
  return numerical_sentence


In [14]:
input_numerical_sentences=[]

for sentence in input_sentences:
  input_numerical_sentences.append(text_to_indices(word_tokenize(sentence.lower()),vocab))

In [16]:
input_numerical_sentences[0]

[1, 2, 3]

In [17]:
len(input_numerical_sentences)

78

In [18]:
training_sequence=[]

for sentence in input_numerical_sentences:
  for i in range(1,len(sentence)):
    training_sequence.append(sentence[:i+1])

In [19]:
len(training_sequence)

942

In [20]:
training_sequence[:5]

[[1, 2], [1, 2, 3], [4, 5], [4, 5, 2], [4, 5, 2, 6]]

In [22]:
len_list=[]

for sequence in training_sequence:
  len_list.append(len(sequence))

max(len_list)

62

In [24]:
padded_training_sequence=[]
for sequence in training_sequence:
  padded_training_sequence.append([0]*(max(len_list)-len(sequence))+sequence)

In [26]:
len(padded_training_sequence[0])

62

In [27]:
padded_training_sequence=torch.tensor(padded_training_sequence,dtype=torch.long)

In [28]:
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   0,   4,   5],
        ...,
        [  0,   0,   0,  ..., 285, 176, 286],
        [  0,   0,   0,  ..., 176, 286, 287],
        [  0,   0,   0,  ..., 286, 287, 288]])

In [29]:
X=padded_training_sequence[:,:-1]
y=padded_training_sequence[:,-1]

In [30]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   0,   0,   4],
        ...,
        [  0,   0,   0,  ...,   0, 285, 176],
        [  0,   0,   0,  ..., 285, 176, 286],
        [  0,   0,   0,  ..., 176, 286, 287]])

In [31]:
y

tensor([  2,   3,   5,   2,   6,   7,   8,   9,  10,  11,   3,  12,  13,  14,
         15,   6,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  18,  26,
         27,  28,  29,  30,   5,   2,  31,  32,  27,   2,   6,  33,  31,  32,
         27,   2,   6,   5,  34,  35,  30,  36,   2,  31,   6,   7,  37,  38,
         39,  34,  40,  28,  41,  12,  42,  30,  15,   5,   2,  43,  27,   2,
         11,   3,  33,  45,  46,  47,   2,  48,  49,  50,  52,  53,   8,   9,
         10,  54,   8,   9,  10,   8,  57,  58,  60,  59,  64,  65,  66,   2,
         67,  43,  68,  69,  70,  50,  71,  72,  58,  73,  74,  46,  17,  75,
         27,  76,   3,  33,  78,  74,  73,  72,  58,  79,  80,  81,  17,  75,
         27,  76,   3,  82,  83,  84,  30,  85,  86,  87,  17,  88,  89,  33,
         45,  86,  90,  17,  91,  27,   2,  89,  33,  93,  94,  95,  80,  96,
         78,  36,  97,  85,  22,  87,  17,  89,  22,  65,  98,  99,  73, 100,
          2,  91,  30,  65,  86, 101,   2, 102, 103,  33,  76, 1

In [32]:
class CustomDataset(Dataset):
  def __init__(self,X,y):
    self.X=X
    self.y=y

  def __len__(self):
    return self.X.shape[0]

  def __getitem__(self,index):
    return self.X[index],self.y[index]

In [33]:
dataset=CustomDataset(X,y)

In [34]:
len(dataset)

942

In [35]:
dataloader=DataLoader(dataset,batch_size=32,shuffle=True)

In [41]:
for input,output in dataloader:
  print(input,output)
  # print(len(output))

tensor([[  0,   0,   0,  ...,  20,  21,  22],
        [  0,   0,   0,  ...,  12,  13,  14],
        [  0,   0,   0,  ...,  38,  15,  22],
        ...,
        [  0,   0,   0,  ..., 100,   2, 131],
        [  0,   0,   0,  ...,   9,  10,  11],
        [  0,   0,   0,  ...,  31,   6,   7]]) tensor([ 23,  15,  45,   9, 176,  32, 135,  45,  86, 152, 219,  44, 223, 184,
        146, 176,  30, 142,   1,   2,  57, 147,  45,  65, 252, 269,   2,  23,
         33,  95,   3,  37])
tensor([[  0,   0,   0,  ...,  34,  40,  28],
        [  0,   0,   0,  ...,  69,  70,  50],
        [  0,   0,   0,  ...,   0,   0, 139],
        ...,
        [  0,   0,   0,  ..., 135,  44,  23],
        [  0,   0,   0,  ..., 153,   2, 154],
        [  0,   0,   0,  ..., 224, 191, 225]]) tensor([ 41,  71,  78, 146, 249,   2, 126,  20,  78,  73,   5,   2,  86,   8,
         24, 131,  31,  43, 184, 163,   2,  30, 262,   2,  86, 127,  95,   2,
        206,  24,  33, 200])
tensor([[  0,   0,   0,  ..., 175,  78,   4],
    

In [42]:
class LSTMModel(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()
    self.embedding=nn.Embedding(vocab_size,100)
    self.lstm=nn.LSTM(100,150,batch_first=True)
    self.fc=nn.Linear(150,vocab_size)

  def forward(self,x):
    embedded=self.embedding(x)
    intermediate_hidden_states,(final_hidden_state,final_cell_state)=self.lstm(embedded)
    output=self.fc(final_hidden_state.squeeze(0))
    return output

In [43]:
model=LSTMModel(len(vocab))

In [59]:
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [46]:
model.to(device)

LSTMModel(
  (embedding): Embedding(289, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=289, bias=True)
)

In [47]:
epochs=50
learning_rate=0.001

criterion=nn.CrossEntropyLoss()

optimizer=torch.optim.Adam(model.parameters(),lr=learning_rate)

In [60]:
for epoch in range(epochs):
  total_loss=0

  for batch_x,batch_y in dataloader:
    batch_x,batch_y=batch_x.to(device),batch_y.to(device)

    optimizer.zero_grad()

    output=model(batch_x)

    loss=criterion(output,batch_y)

    loss.backward()

    optimizer.step()

    total_loss+=loss.item()

  print(f"Epoch: {epoch + 1}, Loss: {total_loss:.4f}")

Epoch: 1, Loss: 4.4392
Epoch: 2, Loss: 4.2579
Epoch: 3, Loss: 4.1943
Epoch: 4, Loss: 4.2150
Epoch: 5, Loss: 4.0637
Epoch: 6, Loss: 4.4434
Epoch: 7, Loss: 3.9852
Epoch: 8, Loss: 4.0692
Epoch: 9, Loss: 4.0526
Epoch: 10, Loss: 3.9160
Epoch: 11, Loss: 3.8657
Epoch: 12, Loss: 3.8209
Epoch: 13, Loss: 3.7651
Epoch: 14, Loss: 3.6998
Epoch: 15, Loss: 3.7533
Epoch: 16, Loss: 3.8084
Epoch: 17, Loss: 3.7114
Epoch: 18, Loss: 3.7549
Epoch: 19, Loss: 3.6700
Epoch: 20, Loss: 3.7135
Epoch: 21, Loss: 3.7623
Epoch: 22, Loss: 3.5722
Epoch: 23, Loss: 3.4426
Epoch: 24, Loss: 3.5149
Epoch: 25, Loss: 3.5820
Epoch: 26, Loss: 3.4755
Epoch: 27, Loss: 3.4420
Epoch: 28, Loss: 3.4845
Epoch: 29, Loss: 3.3872
Epoch: 30, Loss: 3.4678
Epoch: 31, Loss: 3.6138
Epoch: 32, Loss: 3.4410
Epoch: 33, Loss: 3.3326
Epoch: 34, Loss: 3.5772
Epoch: 35, Loss: 3.4831
Epoch: 36, Loss: 3.5753
Epoch: 37, Loss: 3.2904
Epoch: 38, Loss: 3.3820
Epoch: 39, Loss: 3.3760
Epoch: 40, Loss: 3.3256
Epoch: 41, Loss: 3.3752
Epoch: 42, Loss: 3.1999
E

In [63]:
def prediction(model,vocab,text):

  tokenized_text=word_tokenize(text.lower())

  numerical_text=text_to_indices(tokenized_text,vocab)

  padded_text = torch.tensor([0] * (61 - len(numerical_text)) + numerical_text, dtype=torch.long).unsqueeze(0).to(device)

  output=model(padded_text)

  value,index=torch.max(output,dim=1)

  return text + " " + list(vocab.keys())[index]

In [64]:
prediction(model,vocab,"The course follows a monthly")

'The course follows a monthly subscription'

In [65]:
import time

num_tokens=10
input_text="hi how are"

for i in range(num_tokens):
  output_text=prediction(model,vocab,input_text)
  print(output_text)
  input_text=output_text
  time.sleep(0.5)

hi how are the
hi how are the program
hi how are the program follows
hi how are the program follows a
hi how are the program follows a monthly
hi how are the program follows a monthly subscription
hi how are the program follows a monthly subscription model
hi how are the program follows a monthly subscription model .
hi how are the program follows a monthly subscription model . you
hi how are the program follows a monthly subscription model . you have


In [66]:
dataloader1=DataLoader(dataset,batch_size=1,shuffle=True)

In [68]:
def calculate_accuracy(model,dataloader,device):
  # set model for evaluation
  model.eval()
  correct=0
  total=0
  # no need to compute gradients
  with torch.no_grad():
    for batch_x,batch_y in dataloader1:
      batch_x=batch_x.to(device)
      batch_y=batch_y.to(device)

      # get model prediction
      outputs=model(batch_x)

      # get the predicted word indices
      _, predicted=torch.max(outputs,dim=1)

      # compare with actual labels
      correct+=(predicted==batch_y).sum().item()
      total+=batch_y.size(0)

  accuracy=correct/total * 100
  return accuracy

accuracy = calculate_accuracy(model, dataloader, device)
print(f"Model Accuracy: {accuracy:.2f}%")


Model Accuracy: 95.65%
